### ISSUE TITLE
Fail to destroy a session through cm-janus, then always fail to watch a stream

### ISSUE THREAD

**Issue by zazabe** [cargomedia/cm-janus#102]
`janus.destroy()` method send a `"janus": "destroy"` request through the web socket but there's no response from cm-janus:
<img width="686" alt="screen shot 2015-12-08 at 15 42 38" src="https://cloud.githubusercontent.com/assets/401598/11658333/58134b20-9dc2-11e5-82a8-94494a8c6b6c.png">

It works with a direct connection to janus:
![screen shot 2015-12-08 at 15 55 10](https://cloud.githubusercontent.com/assets/401598/11658688/272ab76c-9dc4-11e5-8069-9fed419513c2.png)

Quite strange, because then, it can't connect to the stream anymore, the client never receive the jsep object and can't do the SDP negotiation after a "request": "watch", either with a direct janus connection or through cm-janus:
<img width="696" alt="screen shot 2015-12-08 at 15 52 49" src="https://cloud.githubusercontent.com/assets/401598/11658596/c3927d8e-9dc3-11e5-8b16-38f06dcfdac7.png">

**Comment by zazabe** [comment]
Note that the only solution i found is is restart janus, no need to restart cm-janus or the studio-agent.

**Comment by njam** [comment]
This seems to be fixed with thew newest rtpbroadcast plugin!

@zazabe please confirm

**Comment by njam** [comment]
This seems to be fixed with thew newest rtpbroadcast plugin
