### ISSUE TITLE
Failed to stop a video stream

### ISSUE THREAD

**Issue by zazabe** [cargomedia/cm-janus#109]
Not sure if it's an issue on janus or cm-janus, but there's definitely something wrong with the `rtpbroadcast` plugin.

cm-janus log when the client do a `"request": "stop"`:

```
app debug <- browser {"janus":"message","body":{"request":"stop"},"transaction":"jNTKBusJp4BP","token":"{\"sessionId\":\"feeb77fdd859672948b28c411ffa72a3\"}","session_id":712322919,"handle_id":3045102479}
app debug -> janus {"janus":"message","body":{"request":"stop"},"transaction":"jNTKBusJp4BP","token":"{\"sessionId\":\"feeb77fdd859672948b28c411ffa72a3\"}","session_id":712322919,"handle_id":3045102479}
app debug <- janus {"janus":"ack","session_id":712322919,"transaction":"jNTKBusJp4BP"}
app debug <- janus {"janus":"hangup","session_id":712322919,"sender":3045102479,"reason":"DTLS alert"}
app info cm-api request https://alicex.dev.cargomedia.ch/rpc/null {"method":"CM_Janus_RpcEndpoints.removeStream","params":["mad-panda","mD9ieC9oATnpHVo8HcyjYg__","b9b53ff9-6c31-4ed4-80d5-89a5ce5a5319"]}
app info Removed Plugin{"id":3045102479,"type":"janus.plugin.cm.rtpbroadcast"}
app debug -> browser {"janus":"ack","session_id":712322919,"transaction":"jNTKBusJp4BP"}
app debug -> browser {"janus":"hangup","session_id":712322919,"sender":3045102479,"reason":"DTLS alert"}
app info cm-api response
app debug <- janus {"janus":"event","session_id":712322919,"sender":3045102479,"transaction":"jNTKBusJp4BP","plugindata":{"plugin":"janus.plugin.cm.rtpbroadcast","data":{"streaming":"event","result":{"status":"stopping"}}}}
app info {"transaction":"jNTKBusJp4BP","code":490,"message":"Invalid plugin"}
app debug -> browser {"janus":"error","transaction":"jNTKBusJp4BP","error":{"code":490,"reason":"Invalid plugin"}}
```

We should not have the last janus error response to the browser i suppose...

**Comment by kris-lab** [comment]
This `{"transaction":"jNTKBusJp4BP","code":490,"message":"Invalid plugin"}` looks like `cm-janus` bug? After `stop` we receive multiple `Janus` events like `hangup` and then `stopping` event. 

Looks like the last event `stopping` is not recognized by `cm-janus` due to terminated media session? So basically `cm-janus` receives full `janus` message but proxy this as an error to the browser?

**Comment by tomaszdurka** [comment]
Well. I am not sure if this is really a bug. Currently we manage sessions and plugins in cm-janus. Once we receive `detached` or `hangup` event from janus a plugin is removed and we do not expect any events concerning that plugin anymore. I say it's right. 
Maybe we should not remove the plugin on `hangup` event though.

Another thing is how we handle those events. Probably when event concerning removed plugin is coming from janus server we should ignore it (or maybe proxy?). Seems that sending error to client is wrong indeed.

Questions:
- when should we detach plugin?
  - on `detach`?
  - on `hangup`?
  - on stream `stopping`?
- what to do with removed plugin messages?
  - ignore?
  - proxy?

**Comment by njam** [comment]
@tomaszdurka please update with planned resolution

**Comment by njam** [comment]
@tomaszdurka what is the status here?

**Comment by tomaszdurka** [comment]
We've decided to:
- detach plugin on both `detached` and `hangup` from-janus-events.
- proxy nonexistent plugin messages
