### ISSUE TITLE
Duplicate streams when restarting cm-janus

### ISSUE THREAD

**Issue by njam** [cargomedia/cm-janus#119]
Scenario:
1. Have a mountpoint and a video stream with janus and cm-janus
2. Restart cm-janus
3. Try to re-establish this mountpoint and stream

Problem: When trying to recreate the mountpoint I get "A stream with the provided ID already exists"
- I understand this error comes from janus?
- Does that mean that janus doesn't remove all sessions when cm-janus disconnects from the WebSocket connections?

@tomaszdurka @vogdb

**Comment by tomaszdurka** [comment]
Well if you restart cm-janus you drop all the persistence from it. Meaning it's not possible that this error comes from cm-janus, meaning it comes from janus. I guess stopping node process will stop all the connections attached to it so imo janus should be cleaned.

I think your questions/assumptions are right. Should this issue be added into janus/janus-plugin then?

**Comment by njam** [comment]
Closing in favor of https://github.com/cargomedia/janus-gateway-rtpbroadcast/issues/47
