### ISSUE TITLE
Zombie streams without janus session

### ISSUE THREAD

**Issue by njam** [cargomedia/cm-janus#135]
Multiple streams from the same user on the same channel.
Seems like after some time the janus stream session is already gone, but cm-janus still has entries.

This is problematic because the cleanup mechanism in CM never succeeds (because `stopStream` fails due to the missing session in janus).

Example log:
```
app debug request /stopStream
app info http-client request http://localhost:8300/janus/1689564751/1403815034 {"janus":"detach","transaction":"re33snt4xa"}
app info http-client response {"janus":"error","session_id":1689564751,"transaction":"re33snt4xa","error":{"code":458,"reason":"No such session 1689564751"}}
app warn Stream stop failed {"message":"http-client error: No such session 1689564751"}
```

@tomaszdurka wdyt, what could cause this?
Any good ideas for handling this?

**Comment by njam** [comment]
"timeout" is not considered: https://github.com/cargomedia/cm-janus/issues/137

**Comment by njam** [comment]
@kris-lab can you easily find all cases in janus where a session is destroyed? Maybe there are others we are missing…

**Comment by kris-lab** [comment]
The only cases for session destroy I see:
- `timeout` of session (after 60sec of inactivity)
- `WebSocket` drops
- `attach` if `janus_ice_handle_attach_plugin` returns error
- `dettach` if `janus_ice_handle_destroy` returns error

So I would say that I can imagine if `session` was created and `attach` failed for some reason then session will be destroyed without any extra notification. However `attach` request will get response with error.

**Comment by kris-lab** [comment]
As discussed with @tomaszdurka following are not valid:
- `attach` if janus_ice_handle_attach_plugin returns error
- `dettach` if janus_ice_handle_destroy returns error

**Comment by njam** [comment]
ok great, closing then.
