### ISSUE TITLE
Extract janus client into separate codebase?

### ISSUE THREAD

**Issue by njam** [cargomedia/cm-janus#162]
Reusable in the browser *and* in Node.js.
Let's investigate to see if and how it is feasible.

cc @tomaszdurka @zazabe

**Comment by zazabe** [comment]
:+1:

**Comment by vogdb** [comment]
Ok. Here is the short overview. To extract the most from cm-janus and janus.js into one codebase we need to make them work in the same way. Currently they differ. The main difference is that cm-janus is proxy and janus.js is client. I displayed this difference on the below diagram and it shows that cm-janus handles income and outcome messages independently of each other and janus.js handles them as a whole.
![cm-janus vs janus-js](https://cloud.githubusercontent.com/assets/372386/12702687/5933937c-c840-11e5-87ff-2c099ff788ef.png)
What does it mean in code:
 - cm-janus.
  ```js
  // blue connection on the diagram
  fromClientConnection.on('message', function(request) {
    if('create' == request){
      processedRequest = this.startCreateSession(request);
    }
    if('attach' == request){
      processedRequest = this.startAttachPlugin(request);
    }
    toJanusConnection.send(processedRequest);
  });

  // red connection on the diagram
  toJanusConnection.on('message', function(request) {
    if('create' == request){
      processedRequest = this.finishCreateSession(request);
    }
    if('attach' == request){
      processedRequest = this.finishAttachPlugin(request);
    }
    fromClientConnection.send(processedRequest);
  });
  ```

 - janus.js. As you can see that we wait here for responses in promises.
  ```js
   janusConnection.createSession.then(function(createdSession){})
   Session.attachPlugin.then(function(attachedPlugin){})
  ```

IMO the solution will be to change cm-janus to work as janus.js(client) cause make janus.js(client) to work as cm-janus(proxy) does not make any sense especially if we want to make this client be 3rdparty-available for open-source. It means that cm-janus should wait for response on request. If to show this on a diagram then the solution looks:
![possible solution](https://cloud.githubusercontent.com/assets/372386/12702829/6171890a-c844-11e5-8656-600eaf7ed935.png)
What does it mean in code:
 - cm-janus.
  ```js
  fromClientConnection.on('message', function(request) {
    if('create' == request){
      this.createSession(request).then(function(response){
        fromClientConnection.send(response);
      });
    }
    if('attach' == request){
      this.attachPlugin(request).then(function(response){
        fromClientConnection.send(response);
      });
    }
  });

  toJanusConnection.on('message', function(request) {
    //handles only messages that come from janus on its own like 'hangup' and 'webrtcup'
  });
  ```


Honestly I don't know will this approach succeed but if we keep the things as they are now then we can't extract too much into the janus-core. I would even say that the extracted part will cause more troubles than benefits.

**Comment by vogdb** [comment]
@tomaszdurka @njam @zazabe please look at the above

**Comment by njam** [comment]
I see! So cm-janus would become more like a real janus-client *and* -server, adding a layer in between.

I guess this client should also handle events from janus like `hangup` or `webrtcup`, as they are needed in both the browser and in cm-janus. I imagine this can be done easily by just listening for `message` as you showed it and then emit an event.

**Comment by tomaszdurka** [comment]
Not sure if I got your overview right. Maybe you actually meant similar thing which I try to describe below when saying "proxy should work like client rather then opposite". Let me present:

### WebSocket wrapper
First thing we should and can extract is our wrapper on Websocket connection. It queues messages, promisifies methods, unifies errors, etc.

### Client
Second thing which is similar for both client and proxy is management of sessions, plugins, and transactions. This is something we need in both places (proxy and client). 
Currently main difference I see is:
- in case of proxy we listen for incoming messages on 2 connections, then process them and in case of success we proxy/send them further
- in case of janus.js we listen for incoming and outgoing messages on single (to-janus) connection

What about changing how proxy processes messages?
Instead of making proxy's janus-client work on two connections we could make it work on single `to-janus` connection. This would make it the same as for `janus.js`. We would listen on `send` and `message` "events". We would then put something on top of this `to-janus-connection-client` which would proxy messages on successful events/calls.

### Separate handlers
As wrote above management of sessions, plugins, transactions is common in both cases what is different is how we react on those events. This would need to be extracted. Most likely we would need to have simple classes for registered plugins and additionally different handlers for both `client` and `proxy` apps.

@vogdb @njam wdyt?

**Comment by vogdb** [comment]
> I guess this client should also handle events from janus like `hangup` or `webrtcup`, as they are needed in both the browser and in cm-janus. I imagine this can be done easily by just listening for `message` as you showed it and then emit an event.

Yes!

to @tomaszdurka 
Actually I meant the same as you wrote but you didn't read carefully my review as always :D

**Comment by tomaszdurka** [comment]
@vogdb I did read it carefully couple of times, but I don't find it so understandable.

- nothing about how to actually extract client (sessions, plugins, transactions management)
- nothing about where to put/separate handlers of the plugin events
- code examples are really not understandable; using `this` in no idea what context doesn't help
- from reading "IMO the solution..." I understood that you mean similar thing (that's why wrote that sentence in my comment), but actually code example tells something else; it receives message from `fromClientConnection`, processes it, and sends it back to `fromClientConnection`

**Comment by vogdb** [comment]
> - nothing about how to actually extract client (sessions, plugins, transactions management)

Sessions will go to janus-core. Plugins will not go cause the logic inside them is different for client and proxy. Transactions will go to janus-core cause they are reusable and independent.

> - nothing about where to put/separate handlers of the plugin events

Handlers of plugin events stay in plugins cause logic of handlers is different for proxy and client. So plugins will exist separately for each of them.

> - code examples are really not understandable; using `this` in no idea what context doesn't help

Well. it was just a pseudo-code that was based on JanusProxy.establishConnection. `this` context represented janus.js instance in janus.js code and cm-janus instance in cm-janus code.

> - `fromClientConnection`, processes it, and sends it back to `fromClientConnection`

Well. That's what client does with one difference that client creates janus message on its own and proxy receives already prepared message.

client:
```js
connection.createSession = function() {
  var transaction = this.generateTransactionId();
  var message = {janus: 'create', transaction: transaction/*, other message fields*/};
  var self = this;
  return new Promise(function(resolve, reject) {
    //create transaction with callback
    self.addTransaction(transaction, function(response) {
      if ('success' == response['janus']) {
        resolve(response);
      } else {
        reject(response);
      }
    });
    self.send(message);
  });
};
```

proxy:
```js
connection.createSession = function(message) {
  //message is already created cause we receive it from browser connection!!!
  var self = this;
  return new Promise(function(resolve, reject) {
    //create transaction with callback
    self.addTransaction(message.transaction, function(response) {
      if ('success' == response['janus']) {
        resolve(response);
      } else {
        reject(response);
      }
    });
    self.send(message);
  });
};
```

The above demonstrates us that we can extract this part:
```js
  return new Promise(function(resolve, reject) {
    //create transaction with callback
    self.addTransaction(message.transaction, function(response) {
      if ('success' == response['janus']) {
        resolve(response);
      } else {
        reject(response);
      }
    });
    self.send(message);
  });
};
```

**Comment by vogdb** [comment]
- Introduce expected API
 - Functional acceptance tests

**Comment by vogdb** [comment]
@njam @zazabe @tomaszdurka Please your thoughts about this API:

```js
var janus = new JanusClient({
  token: 'token',
  apisecret: 'apisecret',
  address: 'address'
});

/**
 * @return {Promise}
 */
janus.createConnection().then(function(connection) {
  /**
   * @param {Object} message
   * @return {Promise}
   */
  connection.send({}).then(function(response){});

  connection.on('message', function(message) {});

  /**
   * @return {Boolean}
   */
  connection.isConnected();

  /**
   * @param {Object} message
   * @return {Promise}
   */
  connection.disconnect();

  /**
   * @return {Promise}
   */
  connection.createSession().then(function(session) {

    /**
     * @param {Object} message
     * @return {Promise}
     */
    session.send({}).then(function(response){});

    session.on('message', function(message) {});

    /**
     * @return {Promise}
     */
    session.destroy();

    /**
     * @param {String} name
     * @return {Promise}
     */
    session.attachPlugin('bla').then(function(plugin) {

      /**
       * @param {Object} message
       * @return {Promise}
       */
      plugin.send({}).then(function(response){});

      plugin.on('message', function(message) {});

      /**
       * @return {Promise}
       */
      plugin.detach();
    });
  });
});
```

**Comment by zazabe** [comment]
## About the browser side

Looks good to me and seems to be a good path to escape from the crappy vendor `Janus` client!

It will be straightforward for `vr/janus/client.js`, and for `vr/janus/plugin.js`, we will have to send transactions through this `plugin` instance received after a `session.attachPlugin`, which seems good to me too.

Btw, The biggest tasks on the browser side will be about rewriting the RTC part (RTCPeerConnection, getUserMedia, ICE trickle,...), but it's another story...

**Comment by tomaszdurka** [comment]
Looks good, but not sure about event listeners on each resource. Is there `processMessage` included in this api? Or do we trigger message on each resource no matter what? Also should we have event for outgoing message?

**Comment by vogdb** [comment]
> Is there `processMessage` included in this api?

No. It's needed only for cm-janus.

> Or do we trigger message on each resource no matter what?

Currently yes but we can change it for purposes we need. For example if message belongs to plugin then it skips emitting on connection and session and triggers only on plugin. Of course it happens, if only plugin is represented on connection.

> Also should we have event for outgoing message?

Can't think of a usecase here. Please share your thoughts @tomaszdurka.

**Comment by tomaszdurka** [comment]
What about all the `timeout`, `destroyed`, `detached` events? I understood they will be listened by default on the client, within `processMessage` or shall we have multiple listeners independently?

**Comment by vogdb** [comment]
> What about all the `timeout`, `destroyed`, `detached` events? I understood they will be listened by default on the client, within `processMessage` or shall we have multiple listeners independently?

By default you can receive them by listening on connection message:
```js
  connection.on('message', function(){
    switch (message['janus']) {
      case: 'timeout':
        break;
      case: 'destroyed':
        break;
      //.....
    }
  })
```

**Comment by njam** [comment]
Off topic thought: maybe we should support extensibility of the "transport" from the beginning. Like in [janus-gateway-ruby](https://github.com/cargomedia/janus-gateway-ruby/blob/master/lib/janus_gateway/transport.rb).

**Comment by vogdb** [comment]
@tomaszdurka @njam @zazabe Does it make sense to include webrtc processing into janus-gateway-js library? By webrtc processing I mean plugin methods like `createOffer`, `createAnswer`, `handleRemoteJsep` and etc. Also keepalive polling functionality.
Cm-janus does not need webrtc processing. Only browser client requires webrtc processing.

**Comment by tomaszdurka** [comment]
It's rather question to @zazabe :)

**Comment by zazabe** [comment]
@vogdb I'll rather keep this client for WS communication and do these RTC stuff with something else...

**Comment by vogdb** [comment]
@zazabe Will be suitable for you if I create a second library like `janus-gateway-js-browser`/`janus-gateway-js-webrtc`? and implement webrtc stuff there?

**Comment by zazabe** [comment]
Yes, most of these RTC things are inside the vendor `janus.js` (getUserMedia, SDP negotiation, ICE trickle, etc...) and could be extracted from it. 

There's something about RTCPeerConnection statistics also, but we did our own implementation in `vr/janus/plugin`, I'm not sure if you should integrate it to this new lib or not but we can look into this later...

**Comment by tomaszdurka** [comment]
Work moved into separate project http://github.com/cargomedia/janus-gateway-js.
Reusing new client will be done in #187.
