### ISSUE TITLE
Retry failed jobs regularly

### ISSUE THREAD

**Issue by njam** [cargomedia/cm-janus#164]
Currently they are only retried on restart of the daemon?

We should somehow retry failed jobs regularly, up to X times?
On every failure we should log an error.

@tomaszdurka @vogdb thoughts?

**Comment by vogdb** [comment]
> @tomaszdurka @vogdb thoughts?

Yes we need to retry them! Shall the number of retries be persistent through app restarts?

**Comment by njam** [comment]
I think persistence is not needed. How about we retry 10 times, then abort?
We should also make sure we don't retry *all* previous jobs at the same time, so this should somehow be *throttled*?

**Comment by tomaszdurka** [comment]
Does abort means we remove job and pretend nothing happened? I would rather move job-file somewhere ?

**Comment by njam** [comment]
Or retry forever, with exponential backoff?

**Comment by vogdb** [comment]
> Or retry forever, with exponential backoff?

I like it ^___^

**Comment by njam** [comment]
As researched with Tomasz: maybe use https://github.com/Automattic/kue - which has all the features we want.

**Comment by tomaszdurka** [comment]
This is done in #167 (closing for more clearance).
