### ISSUE TITLE
Send KILL signal to job processes on shutdown

### ISSUE THREAD

**Issue by njam** [cargomedia/cm-janus#181]
Currently we send `TERM` signal. This can potentially lead to detached job processes, if they don't terminate.

I think jobs don't suffer from being killed, so how about we just send `KILL`?

@vogdb @tomaszdurka @kris-lab wdyt?

**Comment by vogdb** [comment]
We send `SIGKILL`
```js
AbstractJob.prototype.cleanup = function() {
  if (this._process) {
    this._process.kill('SIGKILL');
    this._process = null;
  }
```

**Comment by njam** [comment]
Ah!
