### ISSUE TITLE
Origin/edge cluster manager

### ISSUE THREAD

**Issue by njam** [cargomedia/cm-janus#183]
#### When an edge joins the cluster:
1. edge -> clustermanager: **register edge** (HTTP call)
2. clustermanager -> edge1: **start janus session, attach supported plugins** (WebSocket)
3. clustermanager -> origin: **start janus session, attach supported plugins** (WebSocket)
4. clustermanager -> origin: **rtpbroadcast: subscribe to mountpoint updates** (WS)
5. origin -> clustermanager: **rtpbroadcast: initial mountpoint list** (WS)
6. foreach mountpoints:
 - clustermanager -> edge1: **rtpbroadcast: replicate/create mountpoint** (WS)
 -  clustermanager -> origin: **rtpbroadcast: watch udp (viewer: edge1)** (WS)

#### When a mountpoint is created:
1. origin -> clustermanager: **rtpbroadcast: new mountpoint update** (WS)
2. clustermanager -> edge1: **rtpbroadcast: replicate/create mountpoint** (WS)
3. clustermanager -> origin: **rtpbroadcast: watch udp (viewer: edge1)** (WS)

#### When a subscriber connects to `/edge`
- Proxy to an edge, instead of connecting to origin

![img_2280](https://cloud.githubusercontent.com/assets/360800/13295989/b1b93cc4-db2b-11e5-9783-6e2b0bed4a05.jpg)

**Comment by tomaszdurka** [comment]
This issue has transformed into separate project: https://github.com/cargomedia/janus-cluster

**Comment by tomaszdurka** [comment]
Reopening - still needs wiring to external janus-cluster service.

**Comment by tomaszdurka** [comment]
Closing in favor of #186
