### ISSUE TITLE
Error: EMFILE, open '/var/lib/janus/jobs/job-a61ad1a9c5e2d3264e61d1cb8642bcfe.json'

### ISSUE THREAD

**Issue by tomaszdurka** [cargomedia/cm-janus#209]
Possible temporary error on reading files, should we retry?

**Comment by vogdb** [comment]
Yep. There is a library for that. [graceful-fs](https://github.com/isaacs/node-graceful-fs). Should we try it? Also read this article for the explanation http://blog.izs.me/post/56827866110/wtf-is-emfile-and-why-does-it-happen-to-me

**Comment by tomaszdurka** [comment]
For now let's keep it open only.

**Comment by njam** [comment]
Closing in favor of https://github.com/cargomedia/puppet-packages/issues/1233
