### ISSUE TITLE
Connection timeouts

### ISSUE THREAD

**Issue by tomaszdurka** [cargomedia/cm-janus#224]
We have a lot of timeout exceptions (not able to connect to cm-janus)
- Javascript client error: Uncaught TimeoutError: Connecting to stream timed out after 15000ms. ##
- There were also errors on nginx layer
- Could not trace errors connecting to janus, so assume it's cm-janus issue

[Will update issue]

**Comment by njam** [comment]
When I was telnetting to the WebSocket port of cm-janus I could connect, but received no data, the connection just stayed idle.

**Comment by tomaszdurka** [comment]
@vogdb can you confirm this was result of logging issues we had iwth 0.6.6?

**Comment by vogdb** [comment]
Well, it is my guess cause the logging was so heavy-performant but I haven't searched for any proof of this.

**Comment by tomaszdurka** [comment]
Let's close.
