### ISSUE TITLE
cm-api: meaningful error message

### ISSUE THREAD

**Issue by njam** [cargomedia/cm-janus#239]
Message is currently:
> Unexpected rejection error.

Let's make it something meaningful like:
> cm-api call to `/foo` failed

![screen shot 2016-04-06 at 09 45 54](https://cloud.githubusercontent.com/assets/360800/14309380/6133c054-fbdc-11e5-992f-d9d2c611ebd0.png)

**Comment by vogdb** [comment]
I would not do it. The message actually is very informative and useful here. It tells us that `throw new JanusError.CmApi(reason.message);` was somehow ignored by its catch blocks and we caught it as `unhandled rejection`. It's a signal for us that logic of `cm-api-client` still has some holes.

**Comment by njam** [comment]
I see, so "Unexpected rejection error" is some global exception handler.
In that case let's increase its severity, and make sure that we catch this in the future?

**Comment by vogdb** [comment]
> make sure that we catch this in the future?

What do you mean by that? To catch it where it should be caught and not have it as an unhandled rejection error?

**Comment by njam** [comment]
Yes exactly :)

**Comment by tomaszdurka** [comment]
I understand we should change severity of all uncaught exceptions to `fatal`/`critical`.

**Comment by vogdb** [comment]
Yep. It's done in #232
