### ISSUE TITLE
Overview

### ISSUE THREAD

**Issue by kris-lab** [cargomedia/cm-janus#4]
Interact with browsers:
- WebSocket server (proxying to janus)

Interact with CM:
- HTTP client / RPC calls to CM
- HTTP server, receiving requests from CM (with authorization)
- Execute `bin/cm` binary

Interact with Janus:
- WebSocket client (admin channel)

Diagram: https://www.lucidchart.com/documents/edit/10adf617-c9e7-446b-acb5-9b2d0ee55b4e?shared=true

**Comment by kris-lab** [comment]
Again update for this:

> we can receive events from the WebRTC peer (webrtc-up, webrtc-hangup, no audio etc)

What will work for us (tested manually) is:
- streaming (video/audio) plugin: webrtc-up, webrtc-hangup events
- audio bridge plugin: webrtc-up, webrtc-hangup + media events

**Comment by fvovan** [comment]
So if we utilize only direct WS  connection between CM and Janus, will we still need WS server on cm-janus?
