### ISSUE TITLE
Should act on closed WS connection of client

### ISSUE THREAD

**Issue by njam** [cargomedia/cm-janus#87]
When experimenting with cm-janus I was connecting as a client with a WebSocket connection.
When I closed that WebSocket connection nothing happened in cm-janus.

@tomaszdurka we need to close the upstream WS connection in that case, so that janus knows that this client is gone?

**Comment by njam** [comment]
cc @kris-lab

**Comment by vogdb** [comment]
It was already fixed in https://github.com/vogdb/cm-janus/commit/f6367a983d9e064ed77f523dad8907b3857a9ada but this PR wasn't merged. Now the fix is presented in #81 issue. Hope it will be merged :)

**Comment by vogdb** [comment]
Fixed in #81
